backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "background"
    label: "Background"
    files:
      - file: "src/content/background/index.md"
        label: "Background Media"
        name: "media"
        fields:
          - {label: "Content Key", name: "contentKey", widget: hidden, default: "background-media"}
          - {label: "Music Link", name: "musicLink", widget: string}
          - {label: "Font Color", name: fontColor, widget: select, options: ["white", "black"]}
          - {label: "Transition Time (in seconds)", name: transitionTime, widget: string, required: false}
          - label: "Photos"
            name: photos
            widget: list
            fields:
              - {label: "Photo", name: photo, widget: file}

  - name: "socialLinks"
    label: "Social Links"
    folder: "src/content/social-links"
    fields:
      - {label: "Content Key", name: "contentKey", widget: "hidden", default: "social-links"}
      - {label: "Index", name: "index", widget: "hidden"}
      - {label: "Icon", name: "icon", widget: hidden}
      - {label: "Title", name: "title", widget: string}
      - {label: "Link", name: "link", widget: string}
  - name: "musicLinks"
    label: "Music Links"
    folder: "src/content/music-links"
    fields:
      - {label: "Content Key", name: "contentKey", widget: "hidden", default: "music-links"}
      - {label: "Index", name: "index", widget: "hidden"}
      - {label: "Title", name: "title", widget: string}
      - {label: "Link", name: "link", widget: string}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/bio/index.md"
        label: "Bio"
        name: "bio"
        fields:
          - {label: "Template Key", name: "templateKey", widget: hidden, default: "bio-page"}
          - {label: "Body", name: "body", widget: markdown}
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: hidden, default: "contact-page"}
          - label: "Contact categories"
            name: "categories"
            widget: list
            fields:
              - {label: "Category Name", name: "name", widget: string}
              - label: "Contacts"
                name: contacts
                widget: list
                fields:
                  - {label: "Contact Name", name: "name", widget: string}
                  - {label: "Email", name: "email", widget: string}
                  - {label: "Phone Number", name: "phone", widget: string, required: false}
