backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "musicLinks"
    label: "Music Links"
    folder: "src/content/music-links"
    fields:
      - {label: "Content Key", name: "contentKey", widget: "hidden", default: "music-links"}
      - {label: "Index", name: "index", widget: "hidden"}
      - {label: "Title", name: "title", widget: string}
      - {label: "Link", name: "link", widget: string}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/bio/index.md"
        label: "Bio"
        name: "bio"
        fields:
          - {label: "Template Key", name: "templateKey", widget: hidden, default: "bio-page"}
          - {label: "Body", name: "body", widget: markdown}
