backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "musicLinks"
    label: "Music Links"
    folder: "src/content/music-links"
    fields:
      - {label: "Content Key", name: "contentKey", widget: "hidden", default: "music-links"}
      - {label: "Title", name: "title", widget: hidden}
      - {label: "Link", name: "link", widget: string}
  - name: "socialLinks"
    label: "Social Media Links"
    folder: "src/content/src-links"
    fields:
      - {label: "Content Key", name: "contentKey", widget: "hidden", default: "social-links"}
      - {label: "Title", name: "title", widget: hidden}
      - {label: "Link", name: "link", widget: string}
